# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caffeine', models.CharField(blank=True, max_length=50)),
                ('theanine', models.CharField(blank=True, max_length=50)),
                ('carnitine', models.CharField(blank=True, max_length=50)),
                ('tyrosine', models.CharField(blank=True, max_length=50)),
                ('synephrine', models.CharField(blank=True, max_length=50)),
                ('creatine', models.CharField(blank=True, max_length=50)),
                ('hmb', models.CharField(blank=True, max_length=50)),
                ('alpha_gpc', models.CharField(blank=True, max_length=50)),
                ('betaine', models.CharField(blank=True, max_length=50)),
                ('beta_alanine', models.CharField(blank=True, max_length=50)),
                ('citrulline_malate', models.CharField(blank=True, max_length=50)),
                ('bcaa', models.CharField(blank=True, max_length=50)),
                ('beet_root', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
