# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstack',
            name='alpha_gpc',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='bcaa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='beet_root',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='beta_alanine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='betaine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='caffeine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='carnitine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='citrulline_malate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='creatine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='hmb',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='synephrine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='theanine',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customstack',
            name='tyrosine',
            field=models.IntegerField(blank=True),
        ),
    ]
